server:
  port: 8082

spring:
  application:
    name: sample-provider-mcp

jaws:
  application:
    name: ${spring.application.name}
  protocol:
    name: jaws
    serialization: fastjson2
  service:
    export: "jaws:10001"
  registry:
    address: nacos://127.0.0.1:8848
  mcp:
    enabled: true
    server-name: jaws-mcp-demo
    server-version: 1.0.0
    endpoint: /mcp
