server:
  port: 8081
spring:
  application:
    name: sample-consumer-boot

jaws:
  application:
    name: ${spring.application.name}
  protocol:
    name: jaws
    serialization: fastjson2
  registry:
    address: 127.0.0.1
    port: 8848
    protocol: nacos

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0