// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto
// Protobuf Java Version: 4.34.1

package org.hongxi.jaws.wire.health;

@com.google.protobuf.Generated
public final class HealthProto extends com.google.protobuf.GeneratedFile {
  private HealthProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "HealthProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033grpc/health/v1/health.proto\022\016grpc.heal" +
      "th.v1\"%\n\022HealthCheckRequest\022\017\n\007service\030\001" +
      " \001(\t\"\251\001\n\023HealthCheckResponse\022A\n\006status\030\001" +
      " \001(\01621.grpc.health.v1.HealthCheckRespons" +
      "e.ServingStatus\"O\n\rServingStatus\022\013\n\007UNKN" +
      "OWN\020\000\022\013\n\007SERVING\020\001\022\017\n\013NOT_SERVING\020\002\022\023\n\017S" +
      "ERVICE_UNKNOWN\020\0032\256\001\n\006Health\022P\n\005Check\022\".g" +
      "rpc.health.v1.HealthCheckRequest\032#.grpc." +
      "health.v1.HealthCheckResponse\022R\n\005Watch\022\"" +
      ".grpc.health.v1.HealthCheckRequest\032#.grp" +
      "c.health.v1.HealthCheckResponse0\001B,\n\033org" +
      ".hongxi.jaws.wire.healthB\013HealthProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_health_v1_HealthCheckRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_grpc_health_v1_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthCheckRequest_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_grpc_health_v1_HealthCheckResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_grpc_health_v1_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
