spring:
  application:
    name: sample-boot-provider

jaws:
  application:
    name: ${spring.application.name}
  protocol:
    name: jaws
    port: 10000
    serialization: fastjson2
    heartbeat: 30000
  registry:
    address: nacos://127.0.0.1:8848

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.hongxi.jaws.transport.netty.HeartbeatHandler: DEBUG