spring:
  application:
    name: sample-provider-http2

jaws:
  application:
    name: ${spring.application.name}
  protocol:
    name: jaws
    port: 10001
    transport-factory: http2
    serialization: fastjson2
  registry:
    address: nacos://127.0.0.1:8848
