server:
  port: 8080

spring:
  application:
    name: sample-provider-boot

jaws:
  application:
    name: ${spring.application.name}
  protocol:
    name: jaws
  service:
    export: "jaws:10000"
  registry:
    address: 127.0.0.1
    port: 8848
    protocol: nacos
