server:
  port: 8080

spring:
  application:
    name: sample-provider-boot

jaws:
  application:
    name: ${spring.application.name}
  protocol:
    name: jaws
    serialization: fastjson2
  service:
    export: "jaws:10000"
  registry:
    address: nacos://127.0.0.1:8848

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0