server:
  port: 8088

admin:
  harbor:
    nodes:
      - name: node-1
        url: http://127.0.0.1:19858
      - name: node-2
        url: http://127.0.0.1:19859
      - name: node-3
        url: http://127.0.0.1:19860
