// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/rpc/status.proto
// Protobuf Java Version: 4.36.1

package com.google.rpc;

@com.google.protobuf.Generated
public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.rpc.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
   * </pre>
   *
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   * A developer-facing error message, which should be in English.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * A developer-facing error message, which should be in English.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * A list of messages that carry the error details.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any details = 3;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getDetailsList();
  /**
   * <pre>
   * A list of messages that carry the error details.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any details = 3;</code>
   */
  com.google.protobuf.Any getDetails(int index);
  /**
   * <pre>
   * A list of messages that carry the error details.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any details = 3;</code>
   */
  int getDetailsCount();
  /**
   * <pre>
   * A list of messages that carry the error details.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any details = 3;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getDetailsOrBuilderList();
  /**
   * <pre>
   * A list of messages that carry the error details.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any details = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
      int index);
}
