server:
  port: 8082

spring:
  application:
    name: sample-consumer-grpc

jaws:
  application:
    name: ${spring.application.name}
  protocol:
    name: jaws
    transport-factory: grpc
    serialization: fastjson2
  registry:
    address: nacos://127.0.0.1:8848
