// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nacos_grpc_service.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.harbor.proto;

@com.google.protobuf.Generated
public final class NacosGrpcService extends com.google.protobuf.GeneratedFile {
  private NacosGrpcService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "NacosGrpcService");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Metadata_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030nacos_grpc_service.proto\032\031google/proto" +
      "buf/any.proto\"\203\001\n\010Metadata\022\014\n\004type\030\003 \001(\t" +
      "\022\020\n\010clientIp\030\010 \001(\t\022\'\n\007headers\030\007 \003(\0132\026.Me" +
      "tadata.HeadersEntry\032.\n\014HeadersEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"J\n\007Payload\022\033" +
      "\n\010metadata\030\002 \001(\0132\t.Metadata\022\"\n\004body\030\003 \001(" +
      "\0132\024.google.protobuf.Any2*\n\007Request\022\037\n\007re" +
      "quest\022\010.Payload\032\010.Payload\"\0002>\n\017BiRequest" +
      "Stream\022+\n\017requestBiStream\022\010.Payload\032\010.Pa" +
      "yload\"\000(\0010\001B \n\034org.hongxi.jaws.harbor.pr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_Metadata_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Metadata_descriptor,
        new java.lang.String[] { "Type", "ClientIp", "Headers", });
    internal_static_Metadata_HeadersEntry_descriptor =
      internal_static_Metadata_descriptor.getNestedType(0);
    internal_static_Metadata_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Metadata_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Payload_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Payload_descriptor,
        new java.lang.String[] { "Metadata", "Body", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
