// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nacos_grpc_service.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.harbor.proto;

@com.google.protobuf.Generated
public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Metadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.Metadata metadata = 2;</code>
   * @return The metadata.
   */
  org.hongxi.jaws.harbor.proto.Metadata getMetadata();
  /**
   * <code>.Metadata metadata = 2;</code>
   */
  org.hongxi.jaws.harbor.proto.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>.google.protobuf.Any body = 3;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>.google.protobuf.Any body = 3;</code>
   * @return The body.
   */
  com.google.protobuf.Any getBody();
  /**
   * <code>.google.protobuf.Any body = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
