server:
  port: 8083

spring:
  application:
    name: sample-provider-rest

jaws:
  application:
    name: ${spring.application.name}
  protocol:
    name: jaws
    serialization: fastjson2
    port: 10002
  registry:
    address: nacos://127.0.0.1:8848
  rest:
    enabled: true
    endpoint: /rest
