// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/reflection/v1/reflection.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.wire.reflection;

@com.google.protobuf.Generated
public interface ExtensionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1.ExtensionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Fully-qualified type name. The format should be &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string containing_type = 1;</code>
   * @return The containingType.
   */
  java.lang.String getContainingType();
  /**
   * <pre>
   * Fully-qualified type name. The format should be &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string containing_type = 1;</code>
   * @return The bytes for containingType.
   */
  com.google.protobuf.ByteString
      getContainingTypeBytes();

  /**
   * <code>int32 extension_number = 2;</code>
   * @return The extensionNumber.
   */
  int getExtensionNumber();
}
