// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/reflection/v1/reflection.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.wire.reflection;

/**
 * <pre>
 * Serialized FileDescriptorProto messages sent by the server answering
 * a file_by_filename, file_containing_symbol, or file_containing_extension
 * request.
 * </pre>
 *
 * Protobuf type {@code grpc.reflection.v1.FileDescriptorResponse}
 */
@com.google.protobuf.Generated
public final class FileDescriptorResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1.FileDescriptorResponse)
    FileDescriptorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "FileDescriptorResponse");
  }
  // Use FileDescriptorResponse.newBuilder() to construct.
  private FileDescriptorResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FileDescriptorResponse() {
    fileDescriptorProto_ = emptyList(com.google.protobuf.ByteString.class);
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_FileDescriptorResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_FileDescriptorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_FileDescriptorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.hongxi.jaws.wire.reflection.FileDescriptorResponse.class, org.hongxi.jaws.wire.reflection.FileDescriptorResponse.Builder.class);
  }

  public static final int FILE_DESCRIPTOR_PROTO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> fileDescriptorProto_ =
      emptyList(com.google.protobuf.ByteString.class);
  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1;</code>
   * @return A list containing the fileDescriptorProto.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getFileDescriptorProtoList() {
    return fileDescriptorProto_;
  }
  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1;</code>
   * @return The count of fileDescriptorProto.
   */
  public int getFileDescriptorProtoCount() {
    return fileDescriptorProto_.size();
  }
  /**
   * <pre>
   * Serialized FileDescriptorProto messages. We avoid taking a dependency on
   * descriptor.proto, which uses proto2 only features, by making them opaque
   * bytes instead.
   * </pre>
   *
   * <code>repeated bytes file_descriptor_proto = 1;</code>
   * @param index The index of the element to return.
   * @return The fileDescriptorProto at the given index.
   */
  public com.google.protobuf.ByteString getFileDescriptorProto(int index) {
    return fileDescriptorProto_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < fileDescriptorProto_.size(); i++) {
      output.writeBytes(1, fileDescriptorProto_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < fileDescriptorProto_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(fileDescriptorProto_.get(i));
      }
      size += dataSize;
      size += 1 * getFileDescriptorProtoList().size();
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.hongxi.jaws.wire.reflection.FileDescriptorResponse)) {
      return super.equals(obj);
    }
    org.hongxi.jaws.wire.reflection.FileDescriptorResponse other = (org.hongxi.jaws.wire.reflection.FileDescriptorResponse) obj;

    if (!getFileDescriptorProtoList()
        .equals(other.getFileDescriptorProtoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFileDescriptorProtoCount() > 0) {
      hash = (37 * hash) + FILE_DESCRIPTOR_PROTO_FIELD_NUMBER;
      hash = (53 * hash) + getFileDescriptorProtoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.hongxi.jaws.wire.reflection.FileDescriptorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Serialized FileDescriptorProto messages sent by the server answering
   * a file_by_filename, file_containing_symbol, or file_containing_extension
   * request.
   * </pre>
   *
   * Protobuf type {@code grpc.reflection.v1.FileDescriptorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1.FileDescriptorResponse)
      org.hongxi.jaws.wire.reflection.FileDescriptorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_FileDescriptorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_FileDescriptorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hongxi.jaws.wire.reflection.FileDescriptorResponse.class, org.hongxi.jaws.wire.reflection.FileDescriptorResponse.Builder.class);
    }

    // Construct using org.hongxi.jaws.wire.reflection.FileDescriptorResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fileDescriptorProto_ = emptyList(com.google.protobuf.ByteString.class);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_FileDescriptorResponse_descriptor;
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.FileDescriptorResponse getDefaultInstanceForType() {
      return org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.FileDescriptorResponse build() {
      org.hongxi.jaws.wire.reflection.FileDescriptorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.FileDescriptorResponse buildPartial() {
      org.hongxi.jaws.wire.reflection.FileDescriptorResponse result = new org.hongxi.jaws.wire.reflection.FileDescriptorResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.hongxi.jaws.wire.reflection.FileDescriptorResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        fileDescriptorProto_.makeImmutable();
        result.fileDescriptorProto_ = fileDescriptorProto_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.hongxi.jaws.wire.reflection.FileDescriptorResponse) {
        return mergeFrom((org.hongxi.jaws.wire.reflection.FileDescriptorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.hongxi.jaws.wire.reflection.FileDescriptorResponse other) {
      if (other == org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance()) return this;
      if (!other.fileDescriptorProto_.isEmpty()) {
        if (fileDescriptorProto_.isEmpty()) {
          fileDescriptorProto_ = other.fileDescriptorProto_;
          fileDescriptorProto_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureFileDescriptorProtoIsMutable();
          fileDescriptorProto_.addAll(other.fileDescriptorProto_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureFileDescriptorProtoIsMutable();
              fileDescriptorProto_.add(v);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> fileDescriptorProto_ = emptyList(com.google.protobuf.ByteString.class);
    private void ensureFileDescriptorProtoIsMutable() {
      if (!fileDescriptorProto_.isModifiable()) {
        fileDescriptorProto_ = makeMutableCopy(fileDescriptorProto_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @return A list containing the fileDescriptorProto.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getFileDescriptorProtoList() {
      fileDescriptorProto_.makeImmutable();
      return fileDescriptorProto_;
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @return The count of fileDescriptorProto.
     */
    public int getFileDescriptorProtoCount() {
      return fileDescriptorProto_.size();
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @param index The index of the element to return.
     * @return The fileDescriptorProto at the given index.
     */
    public com.google.protobuf.ByteString getFileDescriptorProto(int index) {
      return fileDescriptorProto_.get(index);
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @param index The index to set the value at.
     * @param value The fileDescriptorProto to set.
     * @return This builder for chaining.
     */
    public Builder setFileDescriptorProto(
        int index, com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      ensureFileDescriptorProtoIsMutable();
      fileDescriptorProto_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @param value The fileDescriptorProto to add.
     * @return This builder for chaining.
     */
    public Builder addFileDescriptorProto(com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      ensureFileDescriptorProtoIsMutable();
      fileDescriptorProto_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @param values The fileDescriptorProto to add.
     * @return This builder for chaining.
     */
    public Builder addAllFileDescriptorProto(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureFileDescriptorProtoIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fileDescriptorProto_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileDescriptorProto() {
      fileDescriptorProto_ = emptyList(com.google.protobuf.ByteString.class);
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1.FileDescriptorResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.reflection.v1.FileDescriptorResponse)
  private static final org.hongxi.jaws.wire.reflection.FileDescriptorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.hongxi.jaws.wire.reflection.FileDescriptorResponse();
  }

  public static org.hongxi.jaws.wire.reflection.FileDescriptorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileDescriptorResponse>
      PARSER = new com.google.protobuf.AbstractParser<FileDescriptorResponse>() {
    @java.lang.Override
    public FileDescriptorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FileDescriptorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileDescriptorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.FileDescriptorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

