// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/reflection/v1/reflection.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.wire.reflection;

/**
 * <pre>
 * A list of ServiceResponse sent by the server answering list_services request.
 * </pre>
 *
 * Protobuf type {@code grpc.reflection.v1.ListServiceResponse}
 */
@com.google.protobuf.Generated
public final class ListServiceResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1.ListServiceResponse)
    ListServiceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListServiceResponse");
  }
  // Use ListServiceResponse.newBuilder() to construct.
  private ListServiceResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListServiceResponse() {
    service_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ListServiceResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ListServiceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ListServiceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.hongxi.jaws.wire.reflection.ListServiceResponse.class, org.hongxi.jaws.wire.reflection.ListServiceResponse.Builder.class);
  }

  public static final int SERVICE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.hongxi.jaws.wire.reflection.ServiceResponse> service_;
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.hongxi.jaws.wire.reflection.ServiceResponse> getServiceList() {
    return service_;
  }
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder> 
      getServiceOrBuilderList() {
    return service_;
  }
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public int getServiceCount() {
    return service_.size();
  }
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ServiceResponse getService(int index) {
    return service_.get(index);
  }
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder getServiceOrBuilder(
      int index) {
    return service_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < service_.size(); i++) {
      output.writeMessage(1, service_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = service_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(service_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.hongxi.jaws.wire.reflection.ListServiceResponse)) {
      return super.equals(obj);
    }
    org.hongxi.jaws.wire.reflection.ListServiceResponse other = (org.hongxi.jaws.wire.reflection.ListServiceResponse) obj;

    if (!getServiceList()
        .equals(other.getServiceList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getServiceCount() > 0) {
      hash = (37 * hash) + SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getServiceList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.hongxi.jaws.wire.reflection.ListServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.hongxi.jaws.wire.reflection.ListServiceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A list of ServiceResponse sent by the server answering list_services request.
   * </pre>
   *
   * Protobuf type {@code grpc.reflection.v1.ListServiceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1.ListServiceResponse)
      org.hongxi.jaws.wire.reflection.ListServiceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ListServiceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ListServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hongxi.jaws.wire.reflection.ListServiceResponse.class, org.hongxi.jaws.wire.reflection.ListServiceResponse.Builder.class);
    }

    // Construct using org.hongxi.jaws.wire.reflection.ListServiceResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (serviceBuilder_ == null) {
        service_ = java.util.Collections.emptyList();
      } else {
        service_ = null;
        serviceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ListServiceResponse_descriptor;
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ListServiceResponse getDefaultInstanceForType() {
      return org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ListServiceResponse build() {
      org.hongxi.jaws.wire.reflection.ListServiceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ListServiceResponse buildPartial() {
      org.hongxi.jaws.wire.reflection.ListServiceResponse result = new org.hongxi.jaws.wire.reflection.ListServiceResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.hongxi.jaws.wire.reflection.ListServiceResponse result) {
      if (serviceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          service_ = java.util.Collections.unmodifiableList(service_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.service_ = service_;
      } else {
        result.service_ = serviceBuilder_.build();
      }
    }

    private void buildPartial0(org.hongxi.jaws.wire.reflection.ListServiceResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.hongxi.jaws.wire.reflection.ListServiceResponse) {
        return mergeFrom((org.hongxi.jaws.wire.reflection.ListServiceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.hongxi.jaws.wire.reflection.ListServiceResponse other) {
      if (other == org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance()) return this;
      if (serviceBuilder_ == null) {
        if (!other.service_.isEmpty()) {
          if (service_.isEmpty()) {
            service_ = other.service_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServiceIsMutable();
            service_.addAll(other.service_);
          }
          onChanged();
        }
      } else {
        if (!other.service_.isEmpty()) {
          if (serviceBuilder_.isEmpty()) {
            serviceBuilder_.dispose();
            serviceBuilder_ = null;
            service_ = other.service_;
            bitField0_ = (bitField0_ & ~0x00000001);
            serviceBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetServiceFieldBuilder() : null;
          } else {
            serviceBuilder_.addAllMessages(other.service_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.hongxi.jaws.wire.reflection.ServiceResponse m =
                  input.readMessage(
                      org.hongxi.jaws.wire.reflection.ServiceResponse.parser(),
                      extensionRegistry);
              if (serviceBuilder_ == null) {
                ensureServiceIsMutable();
                service_.add(m);
              } else {
                serviceBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.hongxi.jaws.wire.reflection.ServiceResponse> service_ =
      java.util.Collections.emptyList();
    private void ensureServiceIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        service_ = new java.util.ArrayList<org.hongxi.jaws.wire.reflection.ServiceResponse>(service_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.hongxi.jaws.wire.reflection.ServiceResponse, org.hongxi.jaws.wire.reflection.ServiceResponse.Builder, org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder> serviceBuilder_;

    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public java.util.List<org.hongxi.jaws.wire.reflection.ServiceResponse> getServiceList() {
      if (serviceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(service_);
      } else {
        return serviceBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public int getServiceCount() {
      if (serviceBuilder_ == null) {
        return service_.size();
      } else {
        return serviceBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public org.hongxi.jaws.wire.reflection.ServiceResponse getService(int index) {
      if (serviceBuilder_ == null) {
        return service_.get(index);
      } else {
        return serviceBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder setService(
        int index, org.hongxi.jaws.wire.reflection.ServiceResponse value) {
      if (serviceBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensureServiceIsMutable();
        service_.set(index, value);
        onChanged();
      } else {
        serviceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder setService(
        int index, org.hongxi.jaws.wire.reflection.ServiceResponse.Builder builderForValue) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        service_.set(index, builderForValue.build());
        onChanged();
      } else {
        serviceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder addService(org.hongxi.jaws.wire.reflection.ServiceResponse value) {
      if (serviceBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensureServiceIsMutable();
        service_.add(value);
        onChanged();
      } else {
        serviceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder addService(
        int index, org.hongxi.jaws.wire.reflection.ServiceResponse value) {
      if (serviceBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensureServiceIsMutable();
        service_.add(index, value);
        onChanged();
      } else {
        serviceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder addService(
        org.hongxi.jaws.wire.reflection.ServiceResponse.Builder builderForValue) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        service_.add(builderForValue.build());
        onChanged();
      } else {
        serviceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder addService(
        int index, org.hongxi.jaws.wire.reflection.ServiceResponse.Builder builderForValue) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        service_.add(index, builderForValue.build());
        onChanged();
      } else {
        serviceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder addAllService(
        java.lang.Iterable<? extends org.hongxi.jaws.wire.reflection.ServiceResponse> values) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, service_);
        onChanged();
      } else {
        serviceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder clearService() {
      if (serviceBuilder_ == null) {
        service_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        serviceBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public Builder removeService(int index) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        service_.remove(index);
        onChanged();
      } else {
        serviceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public org.hongxi.jaws.wire.reflection.ServiceResponse.Builder getServiceBuilder(
        int index) {
      return internalGetServiceFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder getServiceOrBuilder(
        int index) {
      if (serviceBuilder_ == null) {
        return service_.get(index);  } else {
        return serviceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public java.util.List<? extends org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder> 
         getServiceOrBuilderList() {
      if (serviceBuilder_ != null) {
        return serviceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(service_);
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public org.hongxi.jaws.wire.reflection.ServiceResponse.Builder addServiceBuilder() {
      return internalGetServiceFieldBuilder().addBuilder(
          org.hongxi.jaws.wire.reflection.ServiceResponse.getDefaultInstance());
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public org.hongxi.jaws.wire.reflection.ServiceResponse.Builder addServiceBuilder(
        int index) {
      return internalGetServiceFieldBuilder().addBuilder(
          index, org.hongxi.jaws.wire.reflection.ServiceResponse.getDefaultInstance());
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
     */
    public java.util.List<org.hongxi.jaws.wire.reflection.ServiceResponse.Builder> 
         getServiceBuilderList() {
      return internalGetServiceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.hongxi.jaws.wire.reflection.ServiceResponse, org.hongxi.jaws.wire.reflection.ServiceResponse.Builder, org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder> 
        internalGetServiceFieldBuilder() {
      if (serviceBuilder_ == null) {
        serviceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.hongxi.jaws.wire.reflection.ServiceResponse, org.hongxi.jaws.wire.reflection.ServiceResponse.Builder, org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder>(
                service_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        service_ = null;
      }
      return serviceBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1.ListServiceResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.reflection.v1.ListServiceResponse)
  private static final org.hongxi.jaws.wire.reflection.ListServiceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.hongxi.jaws.wire.reflection.ListServiceResponse();
  }

  public static org.hongxi.jaws.wire.reflection.ListServiceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListServiceResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListServiceResponse>() {
    @java.lang.Override
    public ListServiceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListServiceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListServiceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ListServiceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

