// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/reflection/v1/reflection.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.wire.reflection;

@com.google.protobuf.Generated
public interface ListServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1.ListServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  java.util.List<org.hongxi.jaws.wire.reflection.ServiceResponse> 
      getServiceList();
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  org.hongxi.jaws.wire.reflection.ServiceResponse getService(int index);
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  int getServiceCount();
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  java.util.List<? extends org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder> 
      getServiceOrBuilderList();
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1.ServiceResponse service = 1;</code>
   */
  org.hongxi.jaws.wire.reflection.ServiceResponseOrBuilder getServiceOrBuilder(
      int index);
}
