// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/reflection/v1/reflection.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.wire.reflection;

/**
 * <pre>
 * The message sent by the server to answer ServerReflectionInfo method.
 * </pre>
 *
 * Protobuf type {@code grpc.reflection.v1.ServerReflectionResponse}
 */
@com.google.protobuf.Generated
public final class ServerReflectionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1.ServerReflectionResponse)
    ServerReflectionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "ServerReflectionResponse");
  }
  // Use ServerReflectionResponse.newBuilder() to construct.
  private ServerReflectionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServerReflectionResponse() {
    validHost_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ServerReflectionResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ServerReflectionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ServerReflectionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.hongxi.jaws.wire.reflection.ServerReflectionResponse.class, org.hongxi.jaws.wire.reflection.ServerReflectionResponse.Builder.class);
  }

  private int bitField0_;
  private int messageResponseCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object messageResponse_;
  public enum MessageResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FILE_DESCRIPTOR_RESPONSE(4),
    ALL_EXTENSION_NUMBERS_RESPONSE(5),
    LIST_SERVICES_RESPONSE(6),
    ERROR_RESPONSE(7),
    MESSAGERESPONSE_NOT_SET(0);
    private final int value;
    private MessageResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageResponseCase forNumber(int value) {
      switch (value) {
        case 4: return FILE_DESCRIPTOR_RESPONSE;
        case 5: return ALL_EXTENSION_NUMBERS_RESPONSE;
        case 6: return LIST_SERVICES_RESPONSE;
        case 7: return ERROR_RESPONSE;
        case 0: return MESSAGERESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageResponseCase
  getMessageResponseCase() {
    return MessageResponseCase.forNumber(
        messageResponseCase_);
  }

  public static final int VALID_HOST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object validHost_ = "";
  /**
   * <code>string valid_host = 1;</code>
   * @return The validHost.
   */
  @java.lang.Override
  public java.lang.String getValidHost() {
    java.lang.Object ref = validHost_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      validHost_ = s;
      return s;
    }
  }
  /**
   * <code>string valid_host = 1;</code>
   * @return The bytes for validHost.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValidHostBytes() {
    java.lang.Object ref = validHost_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      validHost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINAL_REQUEST_FIELD_NUMBER = 2;
  private org.hongxi.jaws.wire.reflection.ServerReflectionRequest originalRequest_;
  /**
   * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
   * @return Whether the originalRequest field is set.
   */
  @java.lang.Override
  public boolean hasOriginalRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
   * @return The originalRequest.
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ServerReflectionRequest getOriginalRequest() {
    return originalRequest_ == null ? org.hongxi.jaws.wire.reflection.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
  }
  /**
   * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ServerReflectionRequestOrBuilder getOriginalRequestOrBuilder() {
    return originalRequest_ == null ? org.hongxi.jaws.wire.reflection.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
  }

  public static final int FILE_DESCRIPTOR_RESPONSE_FIELD_NUMBER = 4;
  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies.
   * As the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
   * @return Whether the fileDescriptorResponse field is set.
   */
  @java.lang.Override
  public boolean hasFileDescriptorResponse() {
    return messageResponseCase_ == 4;
  }
  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies.
   * As the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
   * @return The fileDescriptorResponse.
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.FileDescriptorResponse getFileDescriptorResponse() {
    if (messageResponseCase_ == 4) {
       return (org.hongxi.jaws.wire.reflection.FileDescriptorResponse) messageResponse_;
    }
    return org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies.
   * As the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.FileDescriptorResponseOrBuilder getFileDescriptorResponseOrBuilder() {
    if (messageResponseCase_ == 4) {
       return (org.hongxi.jaws.wire.reflection.FileDescriptorResponse) messageResponse_;
    }
    return org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance();
  }

  public static final int ALL_EXTENSION_NUMBERS_RESPONSE_FIELD_NUMBER = 5;
  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   * @return Whether the allExtensionNumbersResponse field is set.
   */
  @java.lang.Override
  public boolean hasAllExtensionNumbersResponse() {
    return messageResponseCase_ == 5;
  }
  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   * @return The allExtensionNumbersResponse.
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ExtensionNumberResponse getAllExtensionNumbersResponse() {
    if (messageResponseCase_ == 5) {
       return (org.hongxi.jaws.wire.reflection.ExtensionNumberResponse) messageResponse_;
    }
    return org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ExtensionNumberResponseOrBuilder getAllExtensionNumbersResponseOrBuilder() {
    if (messageResponseCase_ == 5) {
       return (org.hongxi.jaws.wire.reflection.ExtensionNumberResponse) messageResponse_;
    }
    return org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.getDefaultInstance();
  }

  public static final int LIST_SERVICES_RESPONSE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * This message is used to answer list_services requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
   * @return Whether the listServicesResponse field is set.
   */
  @java.lang.Override
  public boolean hasListServicesResponse() {
    return messageResponseCase_ == 6;
  }
  /**
   * <pre>
   * This message is used to answer list_services requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
   * @return The listServicesResponse.
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ListServiceResponse getListServicesResponse() {
    if (messageResponseCase_ == 6) {
       return (org.hongxi.jaws.wire.reflection.ListServiceResponse) messageResponse_;
    }
    return org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * This message is used to answer list_services requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ListServiceResponseOrBuilder getListServicesResponseOrBuilder() {
    if (messageResponseCase_ == 6) {
       return (org.hongxi.jaws.wire.reflection.ListServiceResponse) messageResponse_;
    }
    return org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance();
  }

  public static final int ERROR_RESPONSE_FIELD_NUMBER = 7;
  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
   * @return Whether the errorResponse field is set.
   */
  @java.lang.Override
  public boolean hasErrorResponse() {
    return messageResponseCase_ == 7;
  }
  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
   * @return The errorResponse.
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ErrorResponse getErrorResponse() {
    if (messageResponseCase_ == 7) {
       return (org.hongxi.jaws.wire.reflection.ErrorResponse) messageResponse_;
    }
    return org.hongxi.jaws.wire.reflection.ErrorResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
   */
  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ErrorResponseOrBuilder getErrorResponseOrBuilder() {
    if (messageResponseCase_ == 7) {
       return (org.hongxi.jaws.wire.reflection.ErrorResponse) messageResponse_;
    }
    return org.hongxi.jaws.wire.reflection.ErrorResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(validHost_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, validHost_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getOriginalRequest());
    }
    if (messageResponseCase_ == 4) {
      output.writeMessage(4, (org.hongxi.jaws.wire.reflection.FileDescriptorResponse) messageResponse_);
    }
    if (messageResponseCase_ == 5) {
      output.writeMessage(5, (org.hongxi.jaws.wire.reflection.ExtensionNumberResponse) messageResponse_);
    }
    if (messageResponseCase_ == 6) {
      output.writeMessage(6, (org.hongxi.jaws.wire.reflection.ListServiceResponse) messageResponse_);
    }
    if (messageResponseCase_ == 7) {
      output.writeMessage(7, (org.hongxi.jaws.wire.reflection.ErrorResponse) messageResponse_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(validHost_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, validHost_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOriginalRequest());
    }
    if (messageResponseCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (org.hongxi.jaws.wire.reflection.FileDescriptorResponse) messageResponse_);
    }
    if (messageResponseCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (org.hongxi.jaws.wire.reflection.ExtensionNumberResponse) messageResponse_);
    }
    if (messageResponseCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (org.hongxi.jaws.wire.reflection.ListServiceResponse) messageResponse_);
    }
    if (messageResponseCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (org.hongxi.jaws.wire.reflection.ErrorResponse) messageResponse_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.hongxi.jaws.wire.reflection.ServerReflectionResponse)) {
      return super.equals(obj);
    }
    org.hongxi.jaws.wire.reflection.ServerReflectionResponse other = (org.hongxi.jaws.wire.reflection.ServerReflectionResponse) obj;

    if (!getValidHost()
        .equals(other.getValidHost())) return false;
    if (hasOriginalRequest() != other.hasOriginalRequest()) return false;
    if (hasOriginalRequest()) {
      if (!getOriginalRequest()
          .equals(other.getOriginalRequest())) return false;
    }
    if (!getMessageResponseCase().equals(other.getMessageResponseCase())) return false;
    switch (messageResponseCase_) {
      case 4:
        if (!getFileDescriptorResponse()
            .equals(other.getFileDescriptorResponse())) return false;
        break;
      case 5:
        if (!getAllExtensionNumbersResponse()
            .equals(other.getAllExtensionNumbersResponse())) return false;
        break;
      case 6:
        if (!getListServicesResponse()
            .equals(other.getListServicesResponse())) return false;
        break;
      case 7:
        if (!getErrorResponse()
            .equals(other.getErrorResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALID_HOST_FIELD_NUMBER;
    hash = (53 * hash) + getValidHost().hashCode();
    if (hasOriginalRequest()) {
      hash = (37 * hash) + ORIGINAL_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalRequest().hashCode();
    }
    switch (messageResponseCase_) {
      case 4:
        hash = (37 * hash) + FILE_DESCRIPTOR_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getFileDescriptorResponse().hashCode();
        break;
      case 5:
        hash = (37 * hash) + ALL_EXTENSION_NUMBERS_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getAllExtensionNumbersResponse().hashCode();
        break;
      case 6:
        hash = (37 * hash) + LIST_SERVICES_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getListServicesResponse().hashCode();
        break;
      case 7:
        hash = (37 * hash) + ERROR_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.hongxi.jaws.wire.reflection.ServerReflectionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The message sent by the server to answer ServerReflectionInfo method.
   * </pre>
   *
   * Protobuf type {@code grpc.reflection.v1.ServerReflectionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1.ServerReflectionResponse)
      org.hongxi.jaws.wire.reflection.ServerReflectionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ServerReflectionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ServerReflectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hongxi.jaws.wire.reflection.ServerReflectionResponse.class, org.hongxi.jaws.wire.reflection.ServerReflectionResponse.Builder.class);
    }

    // Construct using org.hongxi.jaws.wire.reflection.ServerReflectionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetOriginalRequestFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      validHost_ = "";
      originalRequest_ = null;
      if (originalRequestBuilder_ != null) {
        originalRequestBuilder_.dispose();
        originalRequestBuilder_ = null;
      }
      if (fileDescriptorResponseBuilder_ != null) {
        fileDescriptorResponseBuilder_.clear();
      }
      if (allExtensionNumbersResponseBuilder_ != null) {
        allExtensionNumbersResponseBuilder_.clear();
      }
      if (listServicesResponseBuilder_ != null) {
        listServicesResponseBuilder_.clear();
      }
      if (errorResponseBuilder_ != null) {
        errorResponseBuilder_.clear();
      }
      messageResponseCase_ = 0;
      messageResponse_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionProto.internal_static_grpc_reflection_v1_ServerReflectionResponse_descriptor;
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ServerReflectionResponse getDefaultInstanceForType() {
      return org.hongxi.jaws.wire.reflection.ServerReflectionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ServerReflectionResponse build() {
      org.hongxi.jaws.wire.reflection.ServerReflectionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ServerReflectionResponse buildPartial() {
      org.hongxi.jaws.wire.reflection.ServerReflectionResponse result = new org.hongxi.jaws.wire.reflection.ServerReflectionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.hongxi.jaws.wire.reflection.ServerReflectionResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.validHost_ = validHost_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.originalRequest_ = originalRequestBuilder_ == null
            ? originalRequest_
            : originalRequestBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(org.hongxi.jaws.wire.reflection.ServerReflectionResponse result) {
      result.messageResponseCase_ = messageResponseCase_;
      result.messageResponse_ = this.messageResponse_;
      if (messageResponseCase_ == 4 &&
          fileDescriptorResponseBuilder_ != null) {
        result.messageResponse_ = fileDescriptorResponseBuilder_.build();
      }
      if (messageResponseCase_ == 5 &&
          allExtensionNumbersResponseBuilder_ != null) {
        result.messageResponse_ = allExtensionNumbersResponseBuilder_.build();
      }
      if (messageResponseCase_ == 6 &&
          listServicesResponseBuilder_ != null) {
        result.messageResponse_ = listServicesResponseBuilder_.build();
      }
      if (messageResponseCase_ == 7 &&
          errorResponseBuilder_ != null) {
        result.messageResponse_ = errorResponseBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.hongxi.jaws.wire.reflection.ServerReflectionResponse) {
        return mergeFrom((org.hongxi.jaws.wire.reflection.ServerReflectionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.hongxi.jaws.wire.reflection.ServerReflectionResponse other) {
      if (other == org.hongxi.jaws.wire.reflection.ServerReflectionResponse.getDefaultInstance()) return this;
      if (!other.getValidHost().isEmpty()) {
        validHost_ = other.validHost_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasOriginalRequest()) {
        mergeOriginalRequest(other.getOriginalRequest());
      }
      switch (other.getMessageResponseCase()) {
        case FILE_DESCRIPTOR_RESPONSE: {
          mergeFileDescriptorResponse(other.getFileDescriptorResponse());
          break;
        }
        case ALL_EXTENSION_NUMBERS_RESPONSE: {
          mergeAllExtensionNumbersResponse(other.getAllExtensionNumbersResponse());
          break;
        }
        case LIST_SERVICES_RESPONSE: {
          mergeListServicesResponse(other.getListServicesResponse());
          break;
        }
        case ERROR_RESPONSE: {
          mergeErrorResponse(other.getErrorResponse());
          break;
        }
        case MESSAGERESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              validHost_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetOriginalRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 34: {
              input.readMessage(
                  internalGetFileDescriptorResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageResponseCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetAllExtensionNumbersResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageResponseCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetListServicesResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageResponseCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetErrorResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageResponseCase_ = 7;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageResponseCase_ = 0;
    private java.lang.Object messageResponse_;
    public MessageResponseCase
        getMessageResponseCase() {
      return MessageResponseCase.forNumber(
          messageResponseCase_);
    }

    public Builder clearMessageResponse() {
      messageResponseCase_ = 0;
      messageResponse_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object validHost_ = "";
    /**
     * <code>string valid_host = 1;</code>
     * @return The validHost.
     */
    public java.lang.String getValidHost() {
      java.lang.Object ref = validHost_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        validHost_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string valid_host = 1;</code>
     * @return The bytes for validHost.
     */
    public com.google.protobuf.ByteString
        getValidHostBytes() {
      java.lang.Object ref = validHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        validHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string valid_host = 1;</code>
     * @param value The validHost to set.
     * @return This builder for chaining.
     */
    public Builder setValidHost(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      validHost_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string valid_host = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidHost() {
      validHost_ = getDefaultInstance().getValidHost();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string valid_host = 1;</code>
     * @param value The bytes for validHost to set.
     * @return This builder for chaining.
     */
    public Builder setValidHostBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      validHost_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private org.hongxi.jaws.wire.reflection.ServerReflectionRequest originalRequest_;
    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.ServerReflectionRequest, org.hongxi.jaws.wire.reflection.ServerReflectionRequest.Builder, org.hongxi.jaws.wire.reflection.ServerReflectionRequestOrBuilder> originalRequestBuilder_;
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     * @return Whether the originalRequest field is set.
     */
    public boolean hasOriginalRequest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     * @return The originalRequest.
     */
    public org.hongxi.jaws.wire.reflection.ServerReflectionRequest getOriginalRequest() {
      if (originalRequestBuilder_ == null) {
        return originalRequest_ == null ? org.hongxi.jaws.wire.reflection.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
      } else {
        return originalRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     */
    public Builder setOriginalRequest(org.hongxi.jaws.wire.reflection.ServerReflectionRequest value) {
      if (originalRequestBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        originalRequest_ = value;
      } else {
        originalRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     */
    public Builder setOriginalRequest(
        org.hongxi.jaws.wire.reflection.ServerReflectionRequest.Builder builderForValue) {
      if (originalRequestBuilder_ == null) {
        originalRequest_ = builderForValue.build();
      } else {
        originalRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     */
    public Builder mergeOriginalRequest(org.hongxi.jaws.wire.reflection.ServerReflectionRequest value) {
      if (originalRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          originalRequest_ != null &&
          originalRequest_ != org.hongxi.jaws.wire.reflection.ServerReflectionRequest.getDefaultInstance()) {
          getOriginalRequestBuilder().mergeFrom(value);
        } else {
          originalRequest_ = value;
        }
      } else {
        originalRequestBuilder_.mergeFrom(value);
      }
      if (originalRequest_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     */
    public Builder clearOriginalRequest() {
      bitField0_ = (bitField0_ & ~0x00000002);
      originalRequest_ = null;
      if (originalRequestBuilder_ != null) {
        originalRequestBuilder_.dispose();
        originalRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     */
    public org.hongxi.jaws.wire.reflection.ServerReflectionRequest.Builder getOriginalRequestBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetOriginalRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     */
    public org.hongxi.jaws.wire.reflection.ServerReflectionRequestOrBuilder getOriginalRequestOrBuilder() {
      if (originalRequestBuilder_ != null) {
        return originalRequestBuilder_.getMessageOrBuilder();
      } else {
        return originalRequest_ == null ?
            org.hongxi.jaws.wire.reflection.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
      }
    }
    /**
     * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.ServerReflectionRequest, org.hongxi.jaws.wire.reflection.ServerReflectionRequest.Builder, org.hongxi.jaws.wire.reflection.ServerReflectionRequestOrBuilder> 
        internalGetOriginalRequestFieldBuilder() {
      if (originalRequestBuilder_ == null) {
        originalRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.hongxi.jaws.wire.reflection.ServerReflectionRequest, org.hongxi.jaws.wire.reflection.ServerReflectionRequest.Builder, org.hongxi.jaws.wire.reflection.ServerReflectionRequestOrBuilder>(
                getOriginalRequest(),
                getParentForChildren(),
                isClean());
        originalRequest_ = null;
      }
      return originalRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.FileDescriptorResponse, org.hongxi.jaws.wire.reflection.FileDescriptorResponse.Builder, org.hongxi.jaws.wire.reflection.FileDescriptorResponseOrBuilder> fileDescriptorResponseBuilder_;
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     * @return Whether the fileDescriptorResponse field is set.
     */
    @java.lang.Override
    public boolean hasFileDescriptorResponse() {
      return messageResponseCase_ == 4;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     * @return The fileDescriptorResponse.
     */
    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.FileDescriptorResponse getFileDescriptorResponse() {
      if (fileDescriptorResponseBuilder_ == null) {
        if (messageResponseCase_ == 4) {
          return (org.hongxi.jaws.wire.reflection.FileDescriptorResponse) messageResponse_;
        }
        return org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance();
      } else {
        if (messageResponseCase_ == 4) {
          return fileDescriptorResponseBuilder_.getMessage();
        }
        return org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public Builder setFileDescriptorResponse(org.hongxi.jaws.wire.reflection.FileDescriptorResponse value) {
      if (fileDescriptorResponseBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        messageResponse_ = value;
        onChanged();
      } else {
        fileDescriptorResponseBuilder_.setMessage(value);
      }
      messageResponseCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public Builder setFileDescriptorResponse(
        org.hongxi.jaws.wire.reflection.FileDescriptorResponse.Builder builderForValue) {
      if (fileDescriptorResponseBuilder_ == null) {
        messageResponse_ = builderForValue.build();
        onChanged();
      } else {
        fileDescriptorResponseBuilder_.setMessage(builderForValue.build());
      }
      messageResponseCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public Builder mergeFileDescriptorResponse(org.hongxi.jaws.wire.reflection.FileDescriptorResponse value) {
      if (fileDescriptorResponseBuilder_ == null) {
        if (messageResponseCase_ == 4 &&
            messageResponse_ != org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance()) {
          messageResponse_ = org.hongxi.jaws.wire.reflection.FileDescriptorResponse.newBuilder((org.hongxi.jaws.wire.reflection.FileDescriptorResponse) messageResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          messageResponse_ = value;
        }
        onChanged();
      } else {
        if (messageResponseCase_ == 4) {
          fileDescriptorResponseBuilder_.mergeFrom(value);
        } else {
          fileDescriptorResponseBuilder_.setMessage(value);
        }
      }
      messageResponseCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public Builder clearFileDescriptorResponse() {
      if (fileDescriptorResponseBuilder_ == null) {
        if (messageResponseCase_ == 4) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
          onChanged();
        }
      } else {
        if (messageResponseCase_ == 4) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
        }
        fileDescriptorResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public org.hongxi.jaws.wire.reflection.FileDescriptorResponse.Builder getFileDescriptorResponseBuilder() {
      return internalGetFileDescriptorResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.FileDescriptorResponseOrBuilder getFileDescriptorResponseOrBuilder() {
      if ((messageResponseCase_ == 4) && (fileDescriptorResponseBuilder_ != null)) {
        return fileDescriptorResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageResponseCase_ == 4) {
          return (org.hongxi.jaws.wire.reflection.FileDescriptorResponse) messageResponse_;
        }
        return org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.FileDescriptorResponse, org.hongxi.jaws.wire.reflection.FileDescriptorResponse.Builder, org.hongxi.jaws.wire.reflection.FileDescriptorResponseOrBuilder> 
        internalGetFileDescriptorResponseFieldBuilder() {
      if (fileDescriptorResponseBuilder_ == null) {
        if (!(messageResponseCase_ == 4)) {
          messageResponse_ = org.hongxi.jaws.wire.reflection.FileDescriptorResponse.getDefaultInstance();
        }
        fileDescriptorResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.hongxi.jaws.wire.reflection.FileDescriptorResponse, org.hongxi.jaws.wire.reflection.FileDescriptorResponse.Builder, org.hongxi.jaws.wire.reflection.FileDescriptorResponseOrBuilder>(
                (org.hongxi.jaws.wire.reflection.FileDescriptorResponse) messageResponse_,
                getParentForChildren(),
                isClean());
        messageResponse_ = null;
      }
      messageResponseCase_ = 4;
      onChanged();
      return fileDescriptorResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.ExtensionNumberResponse, org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.Builder, org.hongxi.jaws.wire.reflection.ExtensionNumberResponseOrBuilder> allExtensionNumbersResponseBuilder_;
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     * @return Whether the allExtensionNumbersResponse field is set.
     */
    @java.lang.Override
    public boolean hasAllExtensionNumbersResponse() {
      return messageResponseCase_ == 5;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     * @return The allExtensionNumbersResponse.
     */
    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ExtensionNumberResponse getAllExtensionNumbersResponse() {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (messageResponseCase_ == 5) {
          return (org.hongxi.jaws.wire.reflection.ExtensionNumberResponse) messageResponse_;
        }
        return org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.getDefaultInstance();
      } else {
        if (messageResponseCase_ == 5) {
          return allExtensionNumbersResponseBuilder_.getMessage();
        }
        return org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public Builder setAllExtensionNumbersResponse(org.hongxi.jaws.wire.reflection.ExtensionNumberResponse value) {
      if (allExtensionNumbersResponseBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        messageResponse_ = value;
        onChanged();
      } else {
        allExtensionNumbersResponseBuilder_.setMessage(value);
      }
      messageResponseCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public Builder setAllExtensionNumbersResponse(
        org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.Builder builderForValue) {
      if (allExtensionNumbersResponseBuilder_ == null) {
        messageResponse_ = builderForValue.build();
        onChanged();
      } else {
        allExtensionNumbersResponseBuilder_.setMessage(builderForValue.build());
      }
      messageResponseCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public Builder mergeAllExtensionNumbersResponse(org.hongxi.jaws.wire.reflection.ExtensionNumberResponse value) {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (messageResponseCase_ == 5 &&
            messageResponse_ != org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.getDefaultInstance()) {
          messageResponse_ = org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.newBuilder((org.hongxi.jaws.wire.reflection.ExtensionNumberResponse) messageResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          messageResponse_ = value;
        }
        onChanged();
      } else {
        if (messageResponseCase_ == 5) {
          allExtensionNumbersResponseBuilder_.mergeFrom(value);
        } else {
          allExtensionNumbersResponseBuilder_.setMessage(value);
        }
      }
      messageResponseCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public Builder clearAllExtensionNumbersResponse() {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (messageResponseCase_ == 5) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
          onChanged();
        }
      } else {
        if (messageResponseCase_ == 5) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
        }
        allExtensionNumbersResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.Builder getAllExtensionNumbersResponseBuilder() {
      return internalGetAllExtensionNumbersResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ExtensionNumberResponseOrBuilder getAllExtensionNumbersResponseOrBuilder() {
      if ((messageResponseCase_ == 5) && (allExtensionNumbersResponseBuilder_ != null)) {
        return allExtensionNumbersResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageResponseCase_ == 5) {
          return (org.hongxi.jaws.wire.reflection.ExtensionNumberResponse) messageResponse_;
        }
        return org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.ExtensionNumberResponse, org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.Builder, org.hongxi.jaws.wire.reflection.ExtensionNumberResponseOrBuilder> 
        internalGetAllExtensionNumbersResponseFieldBuilder() {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (!(messageResponseCase_ == 5)) {
          messageResponse_ = org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.getDefaultInstance();
        }
        allExtensionNumbersResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.hongxi.jaws.wire.reflection.ExtensionNumberResponse, org.hongxi.jaws.wire.reflection.ExtensionNumberResponse.Builder, org.hongxi.jaws.wire.reflection.ExtensionNumberResponseOrBuilder>(
                (org.hongxi.jaws.wire.reflection.ExtensionNumberResponse) messageResponse_,
                getParentForChildren(),
                isClean());
        messageResponse_ = null;
      }
      messageResponseCase_ = 5;
      onChanged();
      return allExtensionNumbersResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.ListServiceResponse, org.hongxi.jaws.wire.reflection.ListServiceResponse.Builder, org.hongxi.jaws.wire.reflection.ListServiceResponseOrBuilder> listServicesResponseBuilder_;
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     * @return Whether the listServicesResponse field is set.
     */
    @java.lang.Override
    public boolean hasListServicesResponse() {
      return messageResponseCase_ == 6;
    }
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     * @return The listServicesResponse.
     */
    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ListServiceResponse getListServicesResponse() {
      if (listServicesResponseBuilder_ == null) {
        if (messageResponseCase_ == 6) {
          return (org.hongxi.jaws.wire.reflection.ListServiceResponse) messageResponse_;
        }
        return org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance();
      } else {
        if (messageResponseCase_ == 6) {
          return listServicesResponseBuilder_.getMessage();
        }
        return org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     */
    public Builder setListServicesResponse(org.hongxi.jaws.wire.reflection.ListServiceResponse value) {
      if (listServicesResponseBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        messageResponse_ = value;
        onChanged();
      } else {
        listServicesResponseBuilder_.setMessage(value);
      }
      messageResponseCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     */
    public Builder setListServicesResponse(
        org.hongxi.jaws.wire.reflection.ListServiceResponse.Builder builderForValue) {
      if (listServicesResponseBuilder_ == null) {
        messageResponse_ = builderForValue.build();
        onChanged();
      } else {
        listServicesResponseBuilder_.setMessage(builderForValue.build());
      }
      messageResponseCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     */
    public Builder mergeListServicesResponse(org.hongxi.jaws.wire.reflection.ListServiceResponse value) {
      if (listServicesResponseBuilder_ == null) {
        if (messageResponseCase_ == 6 &&
            messageResponse_ != org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance()) {
          messageResponse_ = org.hongxi.jaws.wire.reflection.ListServiceResponse.newBuilder((org.hongxi.jaws.wire.reflection.ListServiceResponse) messageResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          messageResponse_ = value;
        }
        onChanged();
      } else {
        if (messageResponseCase_ == 6) {
          listServicesResponseBuilder_.mergeFrom(value);
        } else {
          listServicesResponseBuilder_.setMessage(value);
        }
      }
      messageResponseCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     */
    public Builder clearListServicesResponse() {
      if (listServicesResponseBuilder_ == null) {
        if (messageResponseCase_ == 6) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
          onChanged();
        }
      } else {
        if (messageResponseCase_ == 6) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
        }
        listServicesResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     */
    public org.hongxi.jaws.wire.reflection.ListServiceResponse.Builder getListServicesResponseBuilder() {
      return internalGetListServicesResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     */
    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ListServiceResponseOrBuilder getListServicesResponseOrBuilder() {
      if ((messageResponseCase_ == 6) && (listServicesResponseBuilder_ != null)) {
        return listServicesResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageResponseCase_ == 6) {
          return (org.hongxi.jaws.wire.reflection.ListServiceResponse) messageResponse_;
        }
        return org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer list_services requests.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.ListServiceResponse, org.hongxi.jaws.wire.reflection.ListServiceResponse.Builder, org.hongxi.jaws.wire.reflection.ListServiceResponseOrBuilder> 
        internalGetListServicesResponseFieldBuilder() {
      if (listServicesResponseBuilder_ == null) {
        if (!(messageResponseCase_ == 6)) {
          messageResponse_ = org.hongxi.jaws.wire.reflection.ListServiceResponse.getDefaultInstance();
        }
        listServicesResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.hongxi.jaws.wire.reflection.ListServiceResponse, org.hongxi.jaws.wire.reflection.ListServiceResponse.Builder, org.hongxi.jaws.wire.reflection.ListServiceResponseOrBuilder>(
                (org.hongxi.jaws.wire.reflection.ListServiceResponse) messageResponse_,
                getParentForChildren(),
                isClean());
        messageResponse_ = null;
      }
      messageResponseCase_ = 6;
      onChanged();
      return listServicesResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.ErrorResponse, org.hongxi.jaws.wire.reflection.ErrorResponse.Builder, org.hongxi.jaws.wire.reflection.ErrorResponseOrBuilder> errorResponseBuilder_;
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     * @return Whether the errorResponse field is set.
     */
    @java.lang.Override
    public boolean hasErrorResponse() {
      return messageResponseCase_ == 7;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     * @return The errorResponse.
     */
    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ErrorResponse getErrorResponse() {
      if (errorResponseBuilder_ == null) {
        if (messageResponseCase_ == 7) {
          return (org.hongxi.jaws.wire.reflection.ErrorResponse) messageResponse_;
        }
        return org.hongxi.jaws.wire.reflection.ErrorResponse.getDefaultInstance();
      } else {
        if (messageResponseCase_ == 7) {
          return errorResponseBuilder_.getMessage();
        }
        return org.hongxi.jaws.wire.reflection.ErrorResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     */
    public Builder setErrorResponse(org.hongxi.jaws.wire.reflection.ErrorResponse value) {
      if (errorResponseBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        messageResponse_ = value;
        onChanged();
      } else {
        errorResponseBuilder_.setMessage(value);
      }
      messageResponseCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     */
    public Builder setErrorResponse(
        org.hongxi.jaws.wire.reflection.ErrorResponse.Builder builderForValue) {
      if (errorResponseBuilder_ == null) {
        messageResponse_ = builderForValue.build();
        onChanged();
      } else {
        errorResponseBuilder_.setMessage(builderForValue.build());
      }
      messageResponseCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     */
    public Builder mergeErrorResponse(org.hongxi.jaws.wire.reflection.ErrorResponse value) {
      if (errorResponseBuilder_ == null) {
        if (messageResponseCase_ == 7 &&
            messageResponse_ != org.hongxi.jaws.wire.reflection.ErrorResponse.getDefaultInstance()) {
          messageResponse_ = org.hongxi.jaws.wire.reflection.ErrorResponse.newBuilder((org.hongxi.jaws.wire.reflection.ErrorResponse) messageResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          messageResponse_ = value;
        }
        onChanged();
      } else {
        if (messageResponseCase_ == 7) {
          errorResponseBuilder_.mergeFrom(value);
        } else {
          errorResponseBuilder_.setMessage(value);
        }
      }
      messageResponseCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     */
    public Builder clearErrorResponse() {
      if (errorResponseBuilder_ == null) {
        if (messageResponseCase_ == 7) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
          onChanged();
        }
      } else {
        if (messageResponseCase_ == 7) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
        }
        errorResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     */
    public org.hongxi.jaws.wire.reflection.ErrorResponse.Builder getErrorResponseBuilder() {
      return internalGetErrorResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     */
    @java.lang.Override
    public org.hongxi.jaws.wire.reflection.ErrorResponseOrBuilder getErrorResponseOrBuilder() {
      if ((messageResponseCase_ == 7) && (errorResponseBuilder_ != null)) {
        return errorResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageResponseCase_ == 7) {
          return (org.hongxi.jaws.wire.reflection.ErrorResponse) messageResponse_;
        }
        return org.hongxi.jaws.wire.reflection.ErrorResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.hongxi.jaws.wire.reflection.ErrorResponse, org.hongxi.jaws.wire.reflection.ErrorResponse.Builder, org.hongxi.jaws.wire.reflection.ErrorResponseOrBuilder> 
        internalGetErrorResponseFieldBuilder() {
      if (errorResponseBuilder_ == null) {
        if (!(messageResponseCase_ == 7)) {
          messageResponse_ = org.hongxi.jaws.wire.reflection.ErrorResponse.getDefaultInstance();
        }
        errorResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.hongxi.jaws.wire.reflection.ErrorResponse, org.hongxi.jaws.wire.reflection.ErrorResponse.Builder, org.hongxi.jaws.wire.reflection.ErrorResponseOrBuilder>(
                (org.hongxi.jaws.wire.reflection.ErrorResponse) messageResponse_,
                getParentForChildren(),
                isClean());
        messageResponse_ = null;
      }
      messageResponseCase_ = 7;
      onChanged();
      return errorResponseBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1.ServerReflectionResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.reflection.v1.ServerReflectionResponse)
  private static final org.hongxi.jaws.wire.reflection.ServerReflectionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.hongxi.jaws.wire.reflection.ServerReflectionResponse();
  }

  public static org.hongxi.jaws.wire.reflection.ServerReflectionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerReflectionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ServerReflectionResponse>() {
    @java.lang.Override
    public ServerReflectionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerReflectionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerReflectionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.hongxi.jaws.wire.reflection.ServerReflectionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

