// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/reflection/v1/reflection.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.wire.reflection;

@com.google.protobuf.Generated
public final class ServerReflectionProto extends com.google.protobuf.GeneratedFile {
  private ServerReflectionProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "ServerReflectionProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_reflection_v1_ServerReflectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_reflection_v1_ServerReflectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_reflection_v1_ExtensionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_reflection_v1_ExtensionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_reflection_v1_ServerReflectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_reflection_v1_ServerReflectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_reflection_v1_FileDescriptorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_reflection_v1_FileDescriptorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_reflection_v1_ExtensionNumberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_reflection_v1_ExtensionNumberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_reflection_v1_ListServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_reflection_v1_ListServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_reflection_v1_ServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_reflection_v1_ServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_reflection_v1_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_reflection_v1_ErrorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#grpc/reflection/v1/reflection.proto\022\022g" +
      "rpc.reflection.v1\"\205\002\n\027ServerReflectionRe" +
      "quest\022\014\n\004host\030\001 \001(\t\022\032\n\020file_by_filename\030" +
      "\003 \001(\tH\000\022 \n\026file_containing_symbol\030\004 \001(\tH" +
      "\000\022I\n\031file_containing_extension\030\005 \001(\0132$.g" +
      "rpc.reflection.v1.ExtensionRequestH\000\022\'\n\035" +
      "all_extension_numbers_of_type\030\006 \001(\tH\000\022\027\n" +
      "\rlist_services\030\007 \001(\tH\000B\021\n\017message_reques" +
      "t\"E\n\020ExtensionRequest\022\027\n\017containing_type" +
      "\030\001 \001(\t\022\030\n\020extension_number\030\002 \001(\005\"\270\003\n\030Ser" +
      "verReflectionResponse\022\022\n\nvalid_host\030\001 \001(" +
      "\t\022E\n\020original_request\030\002 \001(\0132+.grpc.refle" +
      "ction.v1.ServerReflectionRequest\022N\n\030file" +
      "_descriptor_response\030\004 \001(\0132*.grpc.reflec" +
      "tion.v1.FileDescriptorResponseH\000\022U\n\036all_" +
      "extension_numbers_response\030\005 \001(\0132+.grpc." +
      "reflection.v1.ExtensionNumberResponseH\000\022" +
      "I\n\026list_services_response\030\006 \001(\0132\'.grpc.r" +
      "eflection.v1.ListServiceResponseH\000\022;\n\016er" +
      "ror_response\030\007 \001(\0132!.grpc.reflection.v1." +
      "ErrorResponseH\000B\022\n\020message_response\"7\n\026F" +
      "ileDescriptorResponse\022\035\n\025file_descriptor" +
      "_proto\030\001 \003(\014\"K\n\027ExtensionNumberResponse\022" +
      "\026\n\016base_type_name\030\001 \001(\t\022\030\n\020extension_num" +
      "ber\030\002 \003(\005\"K\n\023ListServiceResponse\0224\n\007serv" +
      "ice\030\001 \003(\0132#.grpc.reflection.v1.ServiceRe" +
      "sponse\"\037\n\017ServiceResponse\022\014\n\004name\030\001 \001(\t\"" +
      ":\n\rErrorResponse\022\022\n\nerror_code\030\001 \001(\005\022\025\n\r" +
      "error_message\030\002 \001(\t2\211\001\n\020ServerReflection" +
      "\022u\n\024ServerReflectionInfo\022+.grpc.reflecti" +
      "on.v1.ServerReflectionRequest\032,.grpc.ref" +
      "lection.v1.ServerReflectionResponse(\0010\001B" +
      "p\n\037org.hongxi.jaws.wire.reflectionB\025Serv" +
      "erReflectionProtoP\001Z4google.golang.org/g" +
      "rpc/reflection/grpc_reflection_v1b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_reflection_v1_ServerReflectionRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_grpc_reflection_v1_ServerReflectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_reflection_v1_ServerReflectionRequest_descriptor,
        new java.lang.String[] { "Host", "FileByFilename", "FileContainingSymbol", "FileContainingExtension", "AllExtensionNumbersOfType", "ListServices", "MessageRequest", });
    internal_static_grpc_reflection_v1_ExtensionRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_grpc_reflection_v1_ExtensionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_reflection_v1_ExtensionRequest_descriptor,
        new java.lang.String[] { "ContainingType", "ExtensionNumber", });
    internal_static_grpc_reflection_v1_ServerReflectionResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_grpc_reflection_v1_ServerReflectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_reflection_v1_ServerReflectionResponse_descriptor,
        new java.lang.String[] { "ValidHost", "OriginalRequest", "FileDescriptorResponse", "AllExtensionNumbersResponse", "ListServicesResponse", "ErrorResponse", "MessageResponse", });
    internal_static_grpc_reflection_v1_FileDescriptorResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_grpc_reflection_v1_FileDescriptorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_reflection_v1_FileDescriptorResponse_descriptor,
        new java.lang.String[] { "FileDescriptorProto", });
    internal_static_grpc_reflection_v1_ExtensionNumberResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_grpc_reflection_v1_ExtensionNumberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_reflection_v1_ExtensionNumberResponse_descriptor,
        new java.lang.String[] { "BaseTypeName", "ExtensionNumber", });
    internal_static_grpc_reflection_v1_ListServiceResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_grpc_reflection_v1_ListServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_reflection_v1_ListServiceResponse_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_grpc_reflection_v1_ServiceResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_grpc_reflection_v1_ServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_reflection_v1_ServiceResponse_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_grpc_reflection_v1_ErrorResponse_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_grpc_reflection_v1_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_reflection_v1_ErrorResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
