// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/reflection/v1/reflection.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.wire.reflection;

@com.google.protobuf.Generated
public interface ServerReflectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1.ServerReflectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string valid_host = 1;</code>
   * @return The validHost.
   */
  java.lang.String getValidHost();
  /**
   * <code>string valid_host = 1;</code>
   * @return The bytes for validHost.
   */
  com.google.protobuf.ByteString
      getValidHostBytes();

  /**
   * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
   * @return Whether the originalRequest field is set.
   */
  boolean hasOriginalRequest();
  /**
   * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
   * @return The originalRequest.
   */
  org.hongxi.jaws.wire.reflection.ServerReflectionRequest getOriginalRequest();
  /**
   * <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2;</code>
   */
  org.hongxi.jaws.wire.reflection.ServerReflectionRequestOrBuilder getOriginalRequestOrBuilder();

  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies.
   * As the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
   * @return Whether the fileDescriptorResponse field is set.
   */
  boolean hasFileDescriptorResponse();
  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies.
   * As the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
   * @return The fileDescriptorResponse.
   */
  org.hongxi.jaws.wire.reflection.FileDescriptorResponse getFileDescriptorResponse();
  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies.
   * As the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4;</code>
   */
  org.hongxi.jaws.wire.reflection.FileDescriptorResponseOrBuilder getFileDescriptorResponseOrBuilder();

  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   * @return Whether the allExtensionNumbersResponse field is set.
   */
  boolean hasAllExtensionNumbersResponse();
  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   * @return The allExtensionNumbersResponse.
   */
  org.hongxi.jaws.wire.reflection.ExtensionNumberResponse getAllExtensionNumbersResponse();
  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   */
  org.hongxi.jaws.wire.reflection.ExtensionNumberResponseOrBuilder getAllExtensionNumbersResponseOrBuilder();

  /**
   * <pre>
   * This message is used to answer list_services requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
   * @return Whether the listServicesResponse field is set.
   */
  boolean hasListServicesResponse();
  /**
   * <pre>
   * This message is used to answer list_services requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
   * @return The listServicesResponse.
   */
  org.hongxi.jaws.wire.reflection.ListServiceResponse getListServicesResponse();
  /**
   * <pre>
   * This message is used to answer list_services requests.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6;</code>
   */
  org.hongxi.jaws.wire.reflection.ListServiceResponseOrBuilder getListServicesResponseOrBuilder();

  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
   * @return Whether the errorResponse field is set.
   */
  boolean hasErrorResponse();
  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
   * @return The errorResponse.
   */
  org.hongxi.jaws.wire.reflection.ErrorResponse getErrorResponse();
  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1.ErrorResponse error_response = 7;</code>
   */
  org.hongxi.jaws.wire.reflection.ErrorResponseOrBuilder getErrorResponseOrBuilder();

  org.hongxi.jaws.wire.reflection.ServerReflectionResponse.MessageResponseCase getMessageResponseCase();
}
