// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/reflection/v1/reflection.proto
// Protobuf Java Version: 4.36.1

package org.hongxi.jaws.wire.reflection;

@com.google.protobuf.Generated
public interface ServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1.ServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Full name of a registered service, including its package name. The format
   * is &lt;package&gt;.&lt;service&gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
